using ExaminationSystem.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace ExaminationSystem.Models
{
    public class Exam : BaseModel
    {
        [Required]
        [StringLength(100)]
        public string Title { get; set; } = null!;
        public ExamType ExamType { get; set; }
        public int NumberOfQuestions { get; set; }
        public bool IsAutoGenerated { get; set; } = false;

        public int CourseId { get; set; }
        public Course Course { get; set; } = null!;

        public ICollection<StudentExam> ExamStudents { get; set; } = new HashSet<StudentExam>();
        public ICollection<ExamQuestion> ExamQuestions { get; set; } = new HashSet<ExamQuestion>();

    }
}
